# Generated by Django 4.2.5 on 2025-11-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackNumber',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('src', models.CharField(default='', max_length=16)),
                ('dst', models.CharField(default='', max_length=16)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('dial_status', models.CharField(default='', max_length=16)),
                ('service_name', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['created'], name='callback_ca_created_1a8139_idx'), models.Index(fields=['dst'], name='callback_ca_dst_40bf7d_idx'), models.Index(fields=['updated'], name='callback_ca_updated_221daf_idx'), models.Index(fields=['service_name'], name='callback_ca_service_9059dd_idx')],
            },
        ),
    ]
