# Generated by Django 4.2.5 on 2023-10-07 15:00

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_dialplancontext_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musiconholdplaylistentry",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to="moh/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3", "wav"]
                    ),
                    core.models.MusicOnHoldPlaylistEntry.validate_file_extension,
                ],
                verbose_name="Playlist entry file",
            ),
        ),
        migrations.AlterField(
            model_name="queue",
            name="music_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queues",
                to="core.musiconhold",
                verbose_name="Music on hold",
            ),
        ),
    ]
