# Generated by Django 4.2.5 on 2023-10-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trunkgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the routing record', max_length=64, unique=True, verbose_name='Routing Record Name')),
                ('prefix', models.CharField(help_text='Prefix of the routing record', max_length=16, unique=True, verbose_name='Routing Record Prefix')),
                ('dialplan', models.TextField(verbose_name='Extension scenario')),
            ],
            options={
                'verbose_name_plural': '14. Routing Records',
            },
        ),
        migrations.CreateModel(
            name='RoutingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the routing table', max_length=64, unique=True, verbose_name='Routing Table Name')),
                ('routing_records', models.ManyToManyField(blank=True, help_text='Routing records in the routing table', related_name='routing_tables', to='core.routingrecord', verbose_name='Routing Records')),
            ],
            options={
                'verbose_name_plural': '15. Routing Tables',
            },
        ),
    ]
