# Generated by Django 4.2.5 on 2023-12-07 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_configurationfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
