# Generated by Django 4.2.5 on 2023-12-11 12:08
import os

from django.db import migrations

description_for_configuration_files = {
    "asterisk.conf": "Asterisk configuration file",
    "extensions.conf": "Dialplan configuration file",
    "extensions.ael": "Dialplan configuration file",
    "features.conf": "Features configuration file",
    "logger.conf": "Logger configuration file",
    "manager.conf": "Manager configuration file",
    "modules.conf": "Modules configuration file",
    "musiconhold.conf": "Music on hold configuration file",
    "queues.conf": "Queues configuration file",
    "res_parking.conf": "Parking configuration file",
    "pjsip.conf": "SIP configuration file",
    "indications.conf": "Indications configuration file",
    "rtp.conf": "RTP configuration file",
}


def create_basic_cfg(apps, schema_editor):
    ConfigurationFile = apps.get_model("core", "ConfigurationFile")
    configs_dir = "contrib/configs"
    etc_asterisk_dir = "/etc/asterisk"

    for filename in os.listdir(configs_dir):
        with open(os.path.join(configs_dir, filename), "r") as file:
            content = file.read()

        path = os.path.join(etc_asterisk_dir, filename)
        description = description_for_configuration_files.get(
            filename, f"{filename} configuration file"
        )

        # Create a ConfigurationFile instance
        ConfigurationFile.objects.create(
            name=filename,
            description=description,
            content=content,
            path=path,
            version=1,  # Set the version as needed
        )


def remove_basic_cfg(apps, schema_editor):
    ConfigurationFile = apps.get_model("core", "ConfigurationFile")
    ConfigurationFile.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_configurationfile_created"),
    ]

    operations = [
        migrations.RunPython(create_basic_cfg, remove_basic_cfg),
    ]
