# Generated by Django 4.2.5 on 2024-02-04 11:57

from django.db import migrations


def create_settings(apps, schema_editor):
    Settings = apps.get_model("core", "Settings")
    Settings.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_macro_normalization_calls'),
    ]

    operations = [
        migrations.RunPython(create_settings),
    ]
