# Generated by Django 4.2.5 on 2024-02-04 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_settings_allow_monitor_alter_settings_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routingtable',
            name='directions',
        ),
    ]
