# Generated by Django 4.2.5 on 2024-09-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_remove_routingtable_directions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="ip_addr_of_grpc_helper",
        ),
        migrations.AddField(
            model_name="settings",
            name="django_manager_secret",
            field=models.CharField(
                default="HLNvg2VQ2Ffu-QqQcQpFz8sFHvZpunPMRd4-6u3hFswX2EMT5CkFEtMwFAFt8LwROGgJBXlZWg6fu-qx969QwA",
                help_text="Secret for Django manager user",
                max_length=64,
                unique=True,
                verbose_name="Django manager secret",
            ),
        ),
    ]
