# Generated by Django 4.2.5 on 2024-09-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_remove_settings_ip_addr_of_grpc_helper_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Use latin symbols, digits and undercore",
                        max_length=32,
                        unique=True,
                        verbose_name="Manager user name",
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="Password for manager user",
                        max_length=64,
                        unique=True,
                        verbose_name="Manager user secret",
                    ),
                ),
                ("read", models.CharField(blank=True, max_length=64, null=True)),
                ("write", models.CharField(blank=True, max_length=64, null=True)),
                ("writetimeout", models.PositiveIntegerField(default=100)),
                (
                    "eventfilter",
                    models.CharField(
                        blank=True,
                        default="!Event: RTCP*|!Event: VarSet|!Event: Cdr",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("deny", models.CharField(blank=True, max_length=64, null=True)),
                ("permit", models.CharField(blank=True, max_length=64, null=True)),
                ("acl", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "verbose_name_plural": "95. Manager users",
                "db_table": "manager_users",
            },
        ),
        migrations.AlterField(
            model_name="settings",
            name="django_manager_secret",
            field=models.CharField(
                default="gZ7OkOa3Wxg6T8mgEPikA1pIdIMZiA1GzEF7-d9kDxx0aAScPcLxYuLE2ckMIOMfscOH4QgnPEtpgMw15tn6hQ",
                help_text="Secret for Django manager user",
                max_length=64,
                unique=True,
                verbose_name="Django manager secret",
            ),
        ),
    ]
