# Generated by Django 4.2.5 on 2024-09-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_managerusers_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerusers',
            old_name='name',
            new_name='username',
        ),
    ]
