# Generated by Django 4.2.5 on 2024-10-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_sipuser_auth_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sipuser",
            name="context",
        ),
        migrations.AlterField(
            model_name="sipuser",
            name="auth_type",
            field=models.CharField(
                blank=True,
                choices=[("userpass", "Plaintext"), ("md5", "MD5")],
                default="userpass",
                help_text="Type of authentication",
                max_length=32,
                null=True,
                verbose_name="Auth type",
            ),
        ),
    ]
