# Generated by Django 4.2.5 on 2024-10-14 07:38

from django.db import migrations
from django.conf import settings


def create_service_context(apps, schema_editor):
    Context = apps.get_model("core", "DialplanContext")
    Context.objects.create(name="local-services", description="Local services context")


def create_echo_service(apps, schema_editor):
    create_service_context(apps, schema_editor)
    Extension = apps.get_model("core", "DialplanExtension")
    Context = apps.get_model("core", "DialplanContext")
    context = Context.objects.get(name="local-services")
    Extension.objects.create(
        context=context,
        ext="130",
        dialplan="""Answer();
Wait(1);
Playback(demo-echotest);
Wait(1);
Echo();
Hangup();
""",
    )
    Extension.objects.create(
        context=context,
        ext="131",
        dialplan="""Answer();
Set(CHANNEL_NAME=${CHANNEL(name)});
Set(ENDPOINT_NAME=${CUT(CHANNEL_NAME,-,1)});
UnPauseQueueMember(,${ENDPOINT_NAME});
Playback(agent-loginok);
Hangup();
""",
    )
    Extension.objects.create(
        context=context,
        ext="132",
        dialplan="""Answer();
Set(CHANNEL_NAME=${CHANNEL(name)});
Set(ENDPOINT_NAME=${CUT(CHANNEL_NAME,-,1)});
PauseQueueMember(,${ENDPOINT_NAME});
Playback(agent-loggedoff);
Hangup();
""",
    )
    create_routing_record(apps, schema_editor)


def create_routing_record(apps, schema_editor):
    Context = apps.get_model("core", "DialplanContext")
    context = Context.objects.get(name="local-services")
    RoutingTable = apps.get_model("core", "RoutingTable")
    routing_table = RoutingTable.objects.get(
        name=settings.PEARLPBX_DEFAULT_ROUTING_TABLE,
    )
    RoutingRecord = apps.get_model("core", "RoutingRecord")
    RoutingRecord.objects.create(
        name="Local Services",
        prefix="_13X",
        context=context,
        routing_table=routing_table,
    )


def remove_echo_service(apps, schema_editor):
    RoutingRecord = apps.get_model("core", "RoutingRecord")
    RoutingRecord.objects.get(prefix="_13X").delete()
    Extension = apps.get_model("core", "DialplanExtension")
    Extension.objects.get(ext="130").delete()
    Context = apps.get_model("core", "DialplanContext")
    Context.objects.get(name="local-services").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_remove_sipuser_context_alter_sipuser_auth_type"),
    ]

    operations = [
        migrations.RunPython(create_echo_service, remove_echo_service),
    ]
