# Generated by Django 4.2.5 on 2025-04-21 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_create_echo_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="django_manager_secret",
        ),
    ]
