# Generated by Django 4.2.5 on 2025-05-17 14:45

import core.models
import core.storages
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_soundfile_alter_musiconholdplaylistentry_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundfile',
            name='language',
            field=models.CharField(blank=True, help_text='Language of the sound file', max_length=3, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storages.SoundsFileSystemStorage(), upload_to=core.models.sound_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'gsm', 'ogg', 'alaw', 'al', 'ulaw', 'ul']), core.models.SoundFile.validate_file_extension, core.models.SoundFile.validate_file_size], verbose_name='Sound file'),
        ),
    ]
