# Generated by Django 4.2.5 on 2025-06-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_monitor_remove_contact_allow_monitor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sippeer",
            name="nat",
            field=models.BooleanField(
                default=False,
                help_text="Enable NAT traversal for this peer",
                verbose_name="NAT",
            ),
        ),
        migrations.AddField(
            model_name="sipuser",
            name="nat",
            field=models.BooleanField(
                default=False,
                help_text="Enable NAT traversal for this peer",
                verbose_name="NAT",
            ),
        ),
    ]
