# Generated by Django 4.2.5 on 2025-06-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_sippeer_nat_sipuser_nat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="user_aor_template",
            field=models.TextField(
                default="type=aor\nmax_contacts=1\nremove_existing=yes\n",
                help_text="You may override it by custom settings in user form",
                verbose_name="User AOR template",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="user_auth_template",
            field=models.TextField(
                default="type=auth\nauth_type=md5\n",
                help_text="You may override it by custom settings in user form",
                verbose_name="User auth template",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="user_template",
            field=models.TextField(
                default="type=endpoint\ncontext=default\nallow=!all, g722, ulaw, alaw\ndirect_media=no\ntrust_id_outbound=yes\ndevice_state_busy_at=1\ndtmf_mode=rfc4733\ntransport=transport-udp-nat\nrtp_symmetric=yes\nforce_rport=yes\nrewrite_contact=yes\n",
                help_text="You may override it by custom settings in user form",
                verbose_name="User basic template",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="webrtc_aor_template",
            field=models.TextField(
                default="type=aor\nmax_contacts=15\nremove_existing=yes\n",
                help_text="You may override it by custom settings in user form",
                verbose_name="WebRTC AOR template",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="webrtc_auth_template",
            field=models.TextField(
                default="type=auth\nauth_type=md5\n",
                help_text="You may override it by custom settings in user form",
                verbose_name="WebRTC auth template",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="webrtc_template",
            field=models.TextField(
                default="\ndtls_auto_generate_cert=yes\nwebrtc=yes\ncontext=default\nmax_audio_streams=1\nmax_video_streams=15\ndisallow=all\nallow=opus,g722,ulaw,vp9,vp8,h264\n",
                help_text="You may override it by custom settings in user form",
                verbose_name="WebRTC template for endpoint",
            ),
        ),
    ]
