# Generated by Django 4.2.5 on 2025-07-19 19:02

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_alter_dialplanextension_ext_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialplancontext",
            name="name",
            field=models.CharField(
                help_text="Unique name for the context or routing tables, use latin symbols, digits and underscores",
                max_length=80,
                unique=True,
                validators=[core.validators.validate_asterisk_context],
                verbose_name="Context name",
            ),
        ),
        migrations.AlterField(
            model_name="routingtable",
            name="name",
            field=models.CharField(
                help_text="Unique name for the routing table and dialplan context, use latin symbols, digits and underscores",
                max_length=80,
                unique=True,
                validators=[core.validators.validate_asterisk_context],
                verbose_name="Routing table name",
            ),
        ),
    ]
