# Generated by Django 4.2.5 on 2025-07-22 12:29

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_alter_dialplancontext_name_alter_routingtable_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialplanextension",
            name="ext",
            field=models.CharField(
                default="_X!",
                help_text="Asterisk extension",
                max_length=64,
                validators=[core.validators.validate_asterisk_extension_prefix],
                verbose_name="Extension",
            ),
        ),
        migrations.AlterField(
            model_name="routingrecord",
            name="prefix",
            field=models.CharField(
                help_text="Prefix of the routing record",
                max_length=64,
                validators=[core.validators.validate_asterisk_extension_prefix],
                verbose_name="Routing Record Prefix",
            ),
        ),
    ]
