# Generated by Django 4.2.5 on 2025-07-22 13:11

from django.db import migrations


def replace_cdr_conf(apps, schema_editor):
    ConfigurationFile = apps.get_model("core", "ConfigurationFile")
    content = """[general]
enable=yes
channeldefaultenabled=yes
unanswered=yes
congestion=no
ignorestatechanges=no
ignoredialchanges=no
endbeforehexten=yes
initiatedseconds=no
batch=no
scheduleronly=no
safeshutdown=yes

[pgsql]
usegmtime=no
loguniqueid=yes
loguserfield=yes
accountlogs=yes
newcdrcolumns=yes
"""
    ConfigurationFile.objects.update_or_create(
        name="cdr.conf",
        version=1,
        defaults={
            "description": "CDR config autogenerated by migration",
            "content": content,
            "path": "/etc/asterisk/cdr.conf",
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_alter_dialplanextension_ext_and_more"),
    ]

    operations = [
        migrations.RunPython(replace_cdr_conf),
    ]
