# Generated by Django 4.2.5 on 2025-07-22 14:11

from django.db import migrations


def create_cdr_pgsql_conf(apps, schema_editor):
    ConfigurationFile = apps.get_model("core", "ConfigurationFile")
    from django.conf import settings

    db_settings = settings.DATABASES["default"]
    content = f"""[global]
hostname={db_settings.get('HOST', 'localhost')}
port={db_settings.get('PORT', '5432')}
dbname={db_settings.get('NAME', 'asterisk')}
password={db_settings.get('PASSWORD', 'password')}
user={db_settings.get('USER', 'postgres')}
;appname=asterisk    ; Postgres application_name support (optional). Whitespace not allowed.
table=cdr              ;SQL table where CDRs will be inserted
;encoding=LATIN9        ; Encoding of logged characters in Asterisk
;timezone=UTC           ; Uncomment if you want datetime fields in UTC/GMT
"""

    ConfigurationFile.objects.update_or_create(
        name="cdr_pgsql.conf",
        version=1,
        defaults={
            "description": "CDR PostgreSQL config autogenerated from Django settings",
            "content": content,
            "path": "/etc/asterisk/cdr_pgsql.conf",
        },
    )

    obj = (
        ConfigurationFile.objects.filter(name="modules.conf")
        .order_by("-version")
        .first()
    )
    if obj:
        content = obj.content
        if "\nload = cdr_pgsql.so" not in content:
            content = content.rstrip() + "\nload = cdr_pgsql.so\n"
            obj.content = content
            obj.save()


def reverse_create_cdr_pgsql_conf(apps, schema_editor):
    ConfigurationFile = apps.get_model("core", "ConfigurationFile")
    ConfigurationFile.objects.filter(name="cdr_pgsql.conf").delete()

    obj = (
        ConfigurationFile.objects.filter(name="modules.conf")
        .order_by("-version")
        .first()
    )
    if obj:
        content = obj.content
        if "\nload = cdr_pgsql.so" in content:
            content = content.replace("\nload = cdr_pgsql.so\n", "\n")
            obj.content = content
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_auto_20250722_1311"),
    ]

    operations = [
        migrations.RunPython(
            create_cdr_pgsql_conf,
            reverse_code=reverse_create_cdr_pgsql_conf,
        ),
    ]
