# Generated by Django 4.2.5 on 2025-08-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_alter_dialplanextension_dialplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialplanextension",
            name="dialplan",
            field=models.TextField(
                help_text="Use Asterisk AEL syntax to define the dialplan.",
                verbose_name="Extension scenario",
            ),
        ),
    ]
