# Generated by Django 4.2.5 on 2025-08-08 11:06

from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Permission
from django.db import migrations


def create_asterisk_permissions(apps, schema_editor):
    """Create custom permissions for Asterisk functionality"""

    # Get or create a content type for our custom permissions
    # Using a generic content type since these aren't tied to specific models
    try:
        content_type = ContentType.objects.get(app_label="auth", model="permission")
    except ContentType.DoesNotExist:
        content_type = ContentType.objects.get_for_model(Permission)

    permissions_to_create = [
        ("view_cdr_report", "Can view CDR reports"),
        ("view_call_recordings", "Can view call recordings"),
        ("view_queue_reports", "Can view queue reports"),
        ("view_callback_statistics", "Can view callback statistics"),
        ("view_autodialer_logs", "Can view AutoDialer logs"),
        ("view_missed_calls_report", "Can view missed calls reports"),
    ]

    for codename, name in permissions_to_create:
        permission, created = Permission.objects.get_or_create(
            codename=codename,
            name=name,
            content_type=content_type,
        )
        if created:
            print(f"Created permission: {name}")
        else:
            print(f"Permission already exists: {name}")


def reverse_asterisk_permissions(apps, schema_editor):
    """Remove the custom permissions"""

    permission_codenames = [
        "view_cdr_report",
        "view_call_recordings",
        "view_queue_reports",
        "view_callback_statistics",
        "view_autodialer_logs",
        "view_missed_calls_report",
    ]

    Permission.objects.filter(codename__in=permission_codenames).delete()
    print("Removed Asterisk custom permissions")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_alter_dialplanextension_dialplan"),
    ]

    operations = [
        migrations.RunPython(
            create_asterisk_permissions,
            reverse_asterisk_permissions,
        ),
    ]
