# Generated by Django 4.2.5 on 2025-08-08 11:07

from django.contrib.auth.models import Group, Permission
from django.db import migrations


def create_report_viewer_group(apps, schema_editor):
    """Create Report Viewer group and assign Asterisk permissions"""

    # Create the group
    group, created = Group.objects.get_or_create(name="Report Viewer")

    if created:
        print("Created group: Report Viewer")
    else:
        print("Group 'Report Viewer' already exists")

    # Permission codenames from the previous migration
    permission_codenames = [
        "view_cdr_report",
        "view_call_recordings",
        "view_queue_reports",
        "view_callback_statistics",
        "view_autodialer_logs",
        "view_missed_calls_report",
    ]

    # Get all permissions and assign them to the group
    permissions = Permission.objects.filter(codename__in=permission_codenames)

    if permissions.exists():
        group.permissions.set(permissions)
        print(f"Assigned {permissions.count()} permissions to 'Report Viewer' group")

        # Print assigned permissions for confirmation
        for perm in permissions:
            print(f"  - {perm.name}")
    else:
        print(
            "Warning: No matching permissions found. Make sure the previous migration ran successfully."
        )


def reverse_report_viewer_group(apps, schema_editor):
    """Remove the Report Viewer group"""

    try:
        group = Group.objects.get(name="Report Viewer")
        group.delete()
        print("Removed 'Report Viewer' group")
    except Group.DoesNotExist:
        print("Group 'Report Viewer' does not exist")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_add_new_permissions"),
    ]

    operations = [
        migrations.RunPython(
            create_report_viewer_group,
            reverse_report_viewer_group,
        ),
    ]
