# Generated by Django 4.2.5 on 2025-08-12 09:12

from django.db import migrations


def create_res_config_pgsql_conf(apps, schema_editor):
    ConfigurationFile = apps.get_model("core", "ConfigurationFile")
    from django.conf import settings

    db_settings = settings.DATABASES["default"]
    content = f"""[general]
dbhost={db_settings.get('HOST', '127.0.0.1')}
dbport={db_settings.get('PORT', '5432')}
dbname={db_settings.get('NAME', 'asterisk')}
dbuser={db_settings.get('USER', 'asterisk')}
dbpass={db_settings.get('PASSWORD', 'password')}
keepalives=1
keepalives_idle=60
keepalives_interval=30
keepalives_count=10
"""

    ConfigurationFile.objects.update_or_create(
        name="res_config_pgsql.conf",
        version=1,
        defaults={
            "description": "Realtime PostgreSQL config autogenerated from Django settings",
            "content": content,
            "path": "/etc/asterisk/res_config_pgsql.conf",
        },
    )
    obj = (
        ConfigurationFile.objects.filter(name="modules.conf")
        .order_by("-version")
        .first()
    )
    if obj:
        content = obj.content
        if "\nload = res_config_pgsql.so" not in content:
            content = content.rstrip() + "\nload = res_config_pgsql.so\n"
            obj.content = content
            obj.save()


def reverse_create_res_config_pgsql_conf(apps, schema_editor):
    ConfigurationFile = apps.get_model("core", "ConfigurationFile")
    ConfigurationFile.objects.filter(name="res_config_pgsql.conf").delete()
    obj = (
        ConfigurationFile.objects.filter(name="modules.conf")
        .order_by("-version")
        .first()
    )
    if obj:
        content = obj.content
        if "\nload = res_config_pgsql.so" in content:
            content = content.replace("\nload = res_config_pgsql.so\n", "\n")
            obj.content = content
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_add_new_group"),
    ]

    operations = [
        migrations.RunPython(
            create_res_config_pgsql_conf,
            reverse_code=reverse_create_res_config_pgsql_conf,
        ),
    ]
