# Generated by Django 4.2.5 on 2025-09-28 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_res_config_pgsql_conf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sipuser",
            name="telephone_type",
        ),
    ]
