# Generated by Django 5.2.8 on 2025-11-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_remove_sipuser_telephone_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dialplancontext',
            table='dialplan_contexts',
        ),
    ]
