# Generated by Django 5.2.8 on 2025-12-28 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_alter_dialplancontext_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sipuser",
            name="integration",
        ),
    ]
