# Generated by Django 5.2.8 on 2026-02-15 17:34

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_alter_soundfile_name_alter_soundfile_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penaltychange",
            name="max_penalty",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Empty=skip, absolute (10) or relative (+3, -2) for QUEUE_MAX_PENALTY",
                max_length=10,
                validators=[core.validators.validate_penalty_value],
            ),
        ),
        migrations.AlterField(
            model_name="penaltychange",
            name="min_penalty",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Empty=skip, absolute (0) or relative (+1, -1) for QUEUE_MIN_PENALTY",
                max_length=10,
                validators=[core.validators.validate_penalty_value],
            ),
        ),
        migrations.AlterField(
            model_name="penaltychange",
            name="raise_penalty",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Empty=skip, absolute (5) or relative (+1, -1) for QUEUE_RAISE_PENALTY",
                max_length=10,
                validators=[core.validators.validate_penalty_value],
            ),
        ),
        migrations.AlterField(
            model_name="queue",
            name="defaultrule",
            field=models.ForeignKey(
                blank=True,
                help_text="Escalation rule from queuerules.conf",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.queuerule",
                verbose_name="Default Rule",
            ),
        ),
    ]
