# Generated by Django 5.2.8 on 2026-03-19 20:40

from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def add_analytics_permission_to_report_viewer(apps, schema_editor):
    try:
        content_type = ContentType.objects.get(app_label="auth", model="permission")
    except ContentType.DoesNotExist:
        content_type = ContentType.objects.get_for_model(Permission)

    permission, created = Permission.objects.get_or_create(
        codename="view_analytics_reports",
        defaults={
            "name": "Can view analytics reports",
            "content_type": content_type,
        },
    )
    if created:
        print("Created permission: Can view analytics reports")

    try:
        group = Group.objects.get(name="Report Viewer")
        group.permissions.add(permission)
        print("Added view_analytics_reports to Report Viewer group")
    except Group.DoesNotExist:
        print("Group 'Report Viewer' does not exist, skipping assignment")


def reverse_analytics_permission(apps, schema_editor):
    try:
        group = Group.objects.get(name="Report Viewer")
        try:
            permission = Permission.objects.get(codename="view_analytics_reports")
            group.permissions.remove(permission)
            permission.delete()
        except Permission.DoesNotExist:
            pass
    except Group.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_add_lists_edit_permissions'),
    ]

    operations = [
        migrations.RunPython(
            add_analytics_permission_to_report_viewer,
            reverse_analytics_permission,
        ),
    ]
