# Generated by Django 5.2.8 on 2026-04-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_add_new_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managerusers",
            name="writetimeout",
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
