# Generated by Django 5.2.8 on 2026-05-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_update_callerid_normalization_idd'),
    ]

    operations = [
        migrations.AddField(
            model_name='siptransport',
            name='allow_reload',
            field=models.BooleanField(default=True, help_text='Allow transport to be reloaded (allow_reload=yes)', verbose_name='Allow reload'),
        ),
        migrations.AddField(
            model_name='siptransport',
            name='verify_server',
            field=models.BooleanField(default=False, help_text='Require and verify the server TLS certificate (verify_server=yes)', verbose_name='Verify server certificate'),
        ),
    ]
