# Generated by Django 5.2.8 on 2026-05-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_siptransport_name_validator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sippeer',
            name='callLimit',
        ),
    ]
