# Generated by Django 5.2.8 on 2026-05-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remove_sippeer_calllimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sippeer',
            name='contact_uri',
            field=models.CharField(blank=True, default='', help_text='Host[:port] for AOR contact (e.g. sbc.provider.com:5061)', max_length=256, null=True, verbose_name='Contact URI host[:port]'),
        ),
        migrations.AddField(
            model_name='sippeer',
            name='match_hosts',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of host[:port] to match incoming calls from provider', max_length=512, null=True, verbose_name='Match hosts'),
        ),
        migrations.AddField(
            model_name='sippeer',
            name='registration_uri',
            field=models.CharField(blank=True, default='', help_text='Host[:port] of the registration server (e.g. reg.provider.com:5060)', max_length=256, null=True, verbose_name='Registration URI host[:port]'),
        ),
    ]
