# Generated by Django 5.2.8 on 2026-05-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_migrate_host_port_to_new_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sippeer',
            name='host_port',
        ),
    ]
