# Generated by Django 5.2.8 on 2026-05-28 09:06

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_remove_host_port_from_sippeer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sippeer',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('userpass', 'Plaintext'), ('md5', 'MD5')], default='userpass', help_text='Type of authentication', max_length=32, null=True, verbose_name='Auth type'),
        ),
        migrations.AddField(
            model_name='sippeer',
            name='contact_user',
            field=models.CharField(blank=True, default='', help_text='Contact user for registration (overrides username if set, e.g. the part after / in user:pass@host/contact_user)', max_length=64, null=True, verbose_name='Contact user'),
        ),
        migrations.AlterField(
            model_name='sippeer',
            name='custom_aor_settings',
            field=models.TextField(blank=True, default='', help_text='Custom peer [aor] section', null=True, verbose_name='AOR Settings'),
        ),
        migrations.AlterField(
            model_name='sippeer',
            name='custom_auth_settings',
            field=models.TextField(blank=True, default='', help_text='Custom peer [auth] section', null=True, verbose_name='Auth Settings'),
        ),
        migrations.AlterField(
            model_name='sippeer',
            name='match_hosts',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of hosts or IPs without ports (e.g. proxy1.provider.com, 192.0.2.1)', max_length=512, null=True, validators=[core.validators.validate_match_hosts], verbose_name='Match hosts'),
        ),
        migrations.AlterField(
            model_name='sipuser',
            name='custom_aor_settings',
            field=models.TextField(blank=True, default='', help_text='Custom user [aor] section', null=True, verbose_name='AOR Settings'),
        ),
        migrations.AlterField(
            model_name='sipuser',
            name='custom_auth_settings',
            field=models.TextField(blank=True, default='', help_text='Custom user [auth] section', null=True, verbose_name='Auth Settings'),
        ),
        migrations.AlterField(
            model_name='sipuser',
            name='custom_extension',
            field=models.TextField(blank=True, default='', help_text='Custom user extension section for incoming calls', null=True, verbose_name='Extension Settings'),
        ),
    ]
