# Generated by Django 5.2.8 on 2026-07-03 13:45

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_add_contact_user_auth_type_to_sippeer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerusers',
            name='secret',
            field=models.CharField(default=core.utils.generate_64_char_password, help_text='Password for manager user', max_length=128, verbose_name='Manager user secret'),
        ),
        migrations.AlterField(
            model_name='sipuser',
            name='secret',
            field=models.CharField(help_text='Password for the connection', max_length=32, verbose_name='Password'),
        ),
    ]
