# Generated by Django 5.2.8 on 2026-07-15 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_whitelist_add_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='callerid',
            field=models.CharField(help_text='Caller ID to block', max_length=64, verbose_name='Caller ID'),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='callerid',
            field=models.CharField(help_text='Caller ID to allow', max_length=64, verbose_name='Caller ID'),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='blacklist',
            constraint=models.UniqueConstraint(fields=('callerid', 'destination'), name='blacklist_callerid_destination_uniq'),
        ),
        migrations.AddConstraint(
            model_name='whitelist',
            constraint=models.UniqueConstraint(fields=('callerid', 'destination'), name='whitelist_callerid_destination_uniq'),
        ),
    ]
