# Generated by Django 5.2.8 on 2026-07-15 12:51

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_blacklist_callerid_alter_whitelist_callerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialplanextension',
            name='dialplan',
            field=models.TextField(help_text='Use Asterisk AEL syntax to define the dialplan.', validators=[core.validators.validate_dialplan_field], verbose_name='Extension scenario'),
        ),
    ]
