# Generated by Django 5.2.8 on 2026-07-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_dialplanextension_dialplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiconhold',
            name='mode',
            field=models.CharField(choices=[('files', 'Files'), ('playlist', 'Playlist'), ('custom', 'Custom')], default='files', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='musiconhold',
            name='sort',
            field=models.CharField(choices=[('random', 'Random'), ('alpha', 'Alpha')], default='random', max_length=32, null=True),
        ),
    ]
