# Generated by Django 5.2.8 on 2026-08-05 09:04

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_create_conference_dialplan_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialplanGlobalVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Latin letters, digits and underscore, must not start with a digit', max_length=64, unique=True, validators=[core.validators.validate_ael_variable_name], verbose_name='Variable name')),
                ('value', models.CharField(help_text='Value assigned in the AEL globals block, Asterisk substitutions are allowed', max_length=255, validators=[core.validators.validate_ael_variable_value], verbose_name='Variable value')),
                ('description', models.CharField(blank=True, help_text='Use latin symbols, digits and undercore to describe', max_length=64, verbose_name='Variable description')),
            ],
            options={
                'verbose_name_plural': '03a. Dialplan globals',
                'db_table': 'dialplan_global_variables',
            },
        ),
    ]
