# Generated by Django 5.2.8 on 2026-08-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_dialplanglobalvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sippeer',
            name='custom_identify_settings',
            field=models.TextField(blank=True, default='', help_text='Custom peer [identify] section body (after endpoint=), e.g. match_header=Contact: 0001', null=True, verbose_name='Identify Settings'),
        ),
    ]
