# Generated by Django 5.2.8 on 2026-08-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_sippeer_custom_identify_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='local_users_dial_template',
            field=models.TextField(default="NoOp(CALL BEGIN >>>> :'${CALLERID(name)}'@<${CALLERID(num)}>);\nSet(CHANNEL(language)=ua);\nSet(TIMEOUT(absolute)=3600);\n&callerid_normalization();\nAGI(agi://127.0.0.1:4573/mixmonitor,${CALLERID(num)},${EXTEN});\nDial(PJSIP/${SIPUser.username},120,rtT);\nHangup();\n", help_text="AEL body used by core.conf.make_local_users_context() for every active SIP user's extension in the auto-generated PEARLPBX-Users context. The placeholder ${SIPUser.username} is substituted per user before rendering; all other ${...} variables (${EXTEN}, ${CALLERID(...)}, etc.) are native Asterisk variables and pass through unchanged.", verbose_name='Local users dial template'),
        ),
    ]
