[general]
; Максимальна кількість одночасних запитів на завершення викликів
cc_max_requests = 10

; Максимальна кількість пристроїв, які можна відстежувати для CCSS
cc_max_monitors = 50

; Зіставлення станів CCSS із станами пристроїв
cc_busy_devstate = INUSE
cc_unavailable_devstate = UNAVAILABLE
cc_available_devstate = NOT_INUSE

; Таймаут для очікування завершення виклику (у секундах)
cc_offer_timer = 7200

; Таймаут для моніторингу стану пристрою (у секундах)
cc_monitor_timer = 3600

; Інтервал між спробами зворотного виклику (у секундах)
cc_recall_timer = 30

; Дозволити або заборонити CCBS (Call Completion on Busy Subscriber)
ccbs_available_timer = 4800
ccbs_enabled = yes

; Дозволити або заборонити CCNR (Call Completion on No Reply)
ccnr_available_timer = 7200
ccnr_enabled = yes

; Політика для моніторингу (generic або specific)
cc_monitor_policy = generic
