; See https://wiki.asterisk.org/wiki/display/AST/Realtime+Database+Configuration
; for basic table formatting information.
[settings]
; Note: The res__pgsql backend configures the database used in their
; respective configuration files and ignore the database name configured in
; this file.
queue_log => pgsql,general

