[general]
use_callids = yes
appendhostname = no
queue_log = yes
queue_log_to_file = yes
queue_log_name = queue_log
queue_log_realtime_use_gmt = no
rotatestrategy = rotate
exec_after_rotate=gzip -9 ${filename}.2

[logfiles]

;debug = verbose,notice,warning,error,debug
console = verbose,notice,warning,error
;messages = verbose,notice,warning,error
full = notice,warning,error,debug,verbose,dtmf,fax
security = security

