---
- name: Restart pearlpbx2-dashboard
  systemd:
    name: pearlpbx2-dashboard
    state: restarted
    daemon_reload: yes

- name: Restart pearlpbx2-callback
  systemd:
    name: pearlpbx2-callback
    state: restarted
    daemon_reload: yes

- name: Restart pearlpbx2-fastagi
  systemd:
    name: pearlpbx2-fastagi
    state: restarted
    daemon_reload: yes
