# Generated by Django 5.2.8 on 2026-07-21 16:51

import apps.webhooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0078_fix_moh_mode_sort_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('url', models.URLField(help_text='Endpoint that receives the JSON POST (CRM side).', max_length=512)),
                ('send_incoming', models.BooleanField(default=True, help_text='Send an event when an incoming call starts.')),
                ('send_ended', models.BooleanField(default=True, help_text='Send an event when a call ends. Only calls announced by an incoming event are reported, so this requires incoming events.')),
                ('send_missed', models.BooleanField(default=False, help_text='Send an event when a caller abandons a queue (missed call).')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Extra HTTP headers, e.g. {"Authorization": "Bearer ..."}.')),
                ('secret', models.CharField(blank=True, default='', help_text='Optional shared secret. When set, requests carry an HMAC-SHA256 signature of the body in the X-PearlPBX-Signature header.', max_length=128)),
                ('timeout', models.PositiveSmallIntegerField(default=5, help_text='HTTP timeout per attempt, seconds.')),
                ('retries', models.PositiveSmallIntegerField(default=1, help_text='Extra delivery attempts after a failure.')),
                ('payload_template', models.JSONField(blank=True, help_text='Optional custom JSON body. String values may use ${placeholders}; empty means the default payload.', null=True, validators=[apps.webhooks.models.validate_payload_template])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('contexts', models.ManyToManyField(blank=True, help_text='Incoming calls entering these contexts trigger the webhook.', related_name='webhooks', to='core.dialplancontext')),
                ('queues', models.ManyToManyField(blank=True, help_text='Calls joining these queues trigger the webhook.', related_name='webhooks', to='core.queue')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'db_table': 'webhook',
            },
        ),
    ]
