# Generated by Django 5.2.8 on 2026-07-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='send_answered',
            field=models.BooleanField(default=False, help_text='Send an event when a queue member answers a call.'),
        ),
    ]
