# Generated by Django 5.2.8 on 2026-07-22 19:59

import apps.webhooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_webhook_send_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='payload_template',
            field=models.JSONField(blank=True, default=apps.webhooks.models.default_payload_template, help_text='Custom JSON body. String values may use ${placeholders}; pre-filled with every available placeholder as a starting point. Clear the field (empty/null) to use the built-in default payload shape instead, which varies per event.', null=True, validators=[apps.webhooks.models.validate_payload_template]),
        ),
    ]
