# Generated by Django 5.2.8 on 2026-08-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_dialplanglobalvariable'),
        ('webhooks', '0003_alter_webhook_payload_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='routing_tables',
            field=models.ManyToManyField(blank=True, help_text="Calls placed by extensions assigned to these routing tables trigger the webhook. A SIP user's PJSIP context is its routing table's name, so this is how outbound calls are matched (DialplanContext only covers inbound-side contexts).", related_name='webhooks', to='core.routingtable'),
        ),
    ]
