# Generated by Django 5.2.8 on 2026-08-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_dialplanglobalvariable'),
        ('webhooks', '0004_webhook_routing_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='send_outgoing',
            field=models.BooleanField(default=False, help_text='Send an event when a SIP user (not a trunk) places an outgoing call.'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='send_outgoing_answered',
            field=models.BooleanField(default=False, help_text='Send an event when the called party answers an outgoing call.'),
        ),
        migrations.AddField(
            model_name='webhook',
            name='send_outgoing_ended',
            field=models.BooleanField(default=False, help_text='Send an event when an outgoing call ends.'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='routing_tables',
            field=models.ManyToManyField(blank=True, help_text='Filters the outgoing-call chain (call.outgoing / call.outgoing_answered / call.outgoing_ended): only calls placed by SIP users assigned to these routing tables trigger it. Trunks (SIPPeer) never trigger the outgoing chain, even if they share a routing table with a SIP user.', related_name='webhooks', to='core.routingtable'),
        ),
    ]
