# Generated by Django 4.2.5 on 2025-07-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QueueLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(blank=True, null=True)),
                ("callid", models.CharField(blank=True, max_length=80)),
                ("queuename", models.CharField(blank=True, max_length=256)),
                ("agent", models.CharField(blank=True, max_length=80)),
                ("event", models.CharField(blank=True, max_length=32)),
                ("data1", models.CharField(blank=True, max_length=100)),
                ("data2", models.CharField(blank=True, max_length=100)),
                ("data3", models.CharField(blank=True, max_length=100)),
                ("data4", models.CharField(blank=True, max_length=100)),
                ("data5", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "queue_log",
                "managed": True,
                "indexes": [
                    models.Index(fields=["time"], name="idx_ql_time"),
                    models.Index(fields=["callid"], name="idx_ql_callid"),
                    models.Index(fields=["queuename"], name="idx_ql_queuename"),
                    models.Index(fields=["agent"], name="idx_ql_agent"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CDR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accountcode", models.CharField(blank=True, max_length=80)),
                ("src", models.CharField(blank=True, max_length=80)),
                ("dst", models.CharField(blank=True, max_length=80)),
                ("dcontext", models.CharField(blank=True, max_length=80)),
                ("clid", models.CharField(blank=True, max_length=80)),
                ("channel", models.CharField(blank=True, max_length=80)),
                ("dstchannel", models.CharField(blank=True, max_length=80)),
                ("lastapp", models.CharField(blank=True, max_length=80)),
                ("lastdata", models.CharField(blank=True, max_length=80)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("answer", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("billsec", models.IntegerField(blank=True, null=True)),
                ("disposition", models.CharField(blank=True, max_length=45)),
                ("amaflags", models.CharField(blank=True, max_length=45)),
                ("userfield", models.CharField(blank=True, max_length=256)),
                ("uniqueid", models.CharField(blank=True, max_length=150)),
                ("linkedid", models.CharField(blank=True, max_length=150)),
                ("peeraccount", models.CharField(blank=True, max_length=80)),
                ("sequence", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "cdr",
                "managed": True,
                "indexes": [
                    models.Index(fields=["src"], name="idx_cdr_src"),
                    models.Index(fields=["dst"], name="idx_cdr_dst"),
                    models.Index(fields=["channel"], name="idx_cdr_channel"),
                    models.Index(fields=["dstchannel"], name="idx_cdr_dstchannel"),
                    models.Index(fields=["start"], name="idx_cdr_start"),
                    models.Index(fields=["end"], name="idx_cdr_end"),
                    models.Index(fields=["duration"], name="idx_cdr_duration"),
                    models.Index(fields=["billsec"], name="idx_cdr_billsec"),
                    models.Index(fields=["disposition"], name="idx_cdr_disposition"),
                    models.Index(fields=["uniqueid"], name="idx_cdr_uniqueid_uniqueid"),
                ],
            },
        ),
    ]
