# Generated by Django 4.2.5 on 2025-08-12 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP INDEX IF EXISTS idx_cdr_uniqueid_uniqueid;",
            reverse_sql="CREATE INDEX idx_cdr_uniqueid_uniqueid ON cdr (uniqueid);",
        ),
        migrations.RunSQL(
            """
            ALTER TABLE cdr DROP CONSTRAINT IF EXISTS cdr_pkey;
            ALTER TABLE cdr ADD COLUMN id SERIAL PRIMARY KEY;
            """,
            reverse_sql="""
            ALTER TABLE cdr DROP COLUMN IF EXISTS id;
            ALTER TABLE cdr ADD PRIMARY KEY (uniqueid);
            """,
        ),
        migrations.RunSQL(
            """
            CREATE INDEX idx_cdr_uniqueid_uniqueid ON cdr (uniqueid);
            CREATE INDEX idx_cdr_linkedid ON cdr (linkedid);
            CREATE INDEX idx_cdr_uniqueid_seq ON cdr (uniqueid, sequence);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_cdr_uniqueid_uniqueid;
            DROP INDEX IF EXISTS idx_cdr_linkedid;
            DROP INDEX IF EXISTS idx_cdr_uniqueid_seq;
            """,
        ),
    ]
