# Generated by Django 5.2.8 on 2025-11-16 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_change_pk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cdr",
            options={"managed": False},
        ),
    ]
