# Generated by Django 4.2.5 on 2025-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_change_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdr',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cdr',
            name='uniqueid',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='cdr',
            unique_together={('uniqueid', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='cdr',
            index=models.Index(fields=['linkedid'], name='idx_cdr_linkedid'),
        ),
        migrations.AddIndex(
            model_name='cdr',
            index=models.Index(fields=['uniqueid', 'sequence'], name='idx_cdr_uniqueid_seq'),
        ),
    ]
