# Generated by Django 5.2.8 on 2026-03-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_cdr_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='queuelog',
            index=models.Index(fields=['event'], name='idx_ql_event'),
        ),
    ]
