# Generated by Django 5.2.8 on 2026-03-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_queuelog_idx_ql_event'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='queuelog',
            index=models.Index(fields=['event', 'callid'], name='idx_ql_event_callid'),
        ),
    ]
